
/////////////////////  MAIN script: replacing abbreviations  //////////////////////////////

// object (dictionary) with abbreviation-full form pairs
var finAcronyms = {
    "CCCN":"Customs Cooperation Council Nomenclature",
    "CPI":"Consumer price index",
    "EC":"European Communities",
    "ECU":"European Currency Unit",
    "EEC":"European Economic Community",
    "EU":"European Union",
    "LDC":"Least Developed Country",
    "FDI":"Foreign Direct Investment",
    "FIR":"Factor intensity reversal",
    "FTA":"Free trade area",
    "RRR":"Required Rate of Return",
    "GATT":"General Agreement on Tariffs and Trade",
    "GDP":"Gross domestic product",
    "GMO":"Genetically modified organism",
    "ICA":"International commodity agreement",
    "ITA":"International Trade Administration",
    "ITC":"International Trade Commission",
    "NAFTA":"North American Free Trade Agreement",
    "NGO":"Non-governmental organization",
    "NIC":"Newly Industrializing Country",
    "NTB":"Nontariff barrier",
    "MNC":"Multinational Corporation",
    "MNE":"Multinational Enterprise",
    "OECD":"Organization for Economic Co-operation and Development",
    "SDR":"Special Drawing Right",
    "TRIP":"Trade-Related Intellectual Property Rights",
    "UNCTAD":"United Nations Conference on Trade and Development",
    "VER":"Voluntary export restraint",
    "WTO":"World Trade Organization",
    "Q1":"Quarter One",
    "Q2":"Quarter Two",
    "Q3":"Quarter Three",
    "Q4":"Quarter Four",
    "1H":"First half of the year",
    "24/7":"24 hours a day",
    "ADR":"Alternative dispute resolution",
    "AI":"Artificial Intelligence",
    "AOP":"Adjusted Operating Profit",
    "AOP":"Annual Operating Plan",
    "AP":"Accounts payable",
    "AR":"Accounts receivable",
    "ARPU":"Average revenue per user",
    "ASP":"Average selling price",
    "agcy":"Agency",
    "agt":"Agent",
    "asst":"Assistant",
    "a/c":"Account",
    "AE":"Account Executive",
    "BAU":"Business As Usual",
    "BEP":"Break Even Point",
    "BIC":"Bank Identifier Code",
    "bldg":"Building",
    "BLS":"Balance sheet",
    "BMC":"Business Model Canvas",
    "BOM":"Bill of materials",
    "BPO":"Business Process Outsourcing",
    "BPR":"Brief Project Report",
    "BPV":"Bank Payment Voucher",
    "BRD":"Business Requirements Document",
    "BRU":"Business Recovery Unit",
    "BRV":"Bank Receipt Voucher",
    "B2B":"Business-to-business",
    "B2C":"Business-to-consumer",
    "B2G":"Business-to-government",
    "BU":"Business Unit",
    "BUSI":"Business",
    "bus":"Business",
    "BFRS":"Bangladesh Financial Reporting Standards",
    "CAGR":"Compound annual growth rate",
    "CAO":"Chief Accounting Officer",
    "CAPEX":"Capital Expenditure",
    "CAPM":"Capital asset pricing model",
    "CBOE":"Chicago Board Options Exchange",
    "CBOT":"Chicago Board of Trade",
    "CDO":"Collateralized Debt Obligation",
    "CDM":"Change and Data Management",
    "CDS":"Credit default swap",
    "CEO":"Chief executive officer",
    "COA":"Chart of Account",
    "CFA":"Chartered Financial Analyst",
    "CFD":"Contract for difference",
    "CFC":"Consumption of fixed capital",
    "CFCT":"Cash Flow Cycle Time",
    "CFM":"Certified Financial Manager",
    "CFO":"Chief Financial Officer",
    "CFS":"Consolidated Financial Statement",
    "CIA":"Certified Internal Auditor",
    "CIF":"Cost Insurance With Freight",
    "CIMA":"Chartered Institute of Management Accountants",
    "CIO":"Chief Information Officer",
    "CIP":"Carriage and Insurance Paid",
    "CISA":"Certified Information Systems Auditor",
    "CISO":"Chief Information Security Officer",
    "CLO":"Chief Legal Officer",
    "CMA":"Certified Management Accountant",
    "CMFB":"Committee on monetary",
    "CMO":"Chief Marketing Officer",
    "COB":"Close of Business",
    "COGS":"Cost of Goods Sold",
    "Corp":"Corporation",
    "COO":"Chief Operating Officer",
    "CPA":"Certified Public Accountant",
    "CPI":"Consumer Price Index",
    "CPO":"Chief Product Officer",
    "CPQ":"Configure",
    "CPU":"Central Processing Unit",
    "CSI":"Corporate Social Investment",
    "CSO":"Chief Security Officer",
    "CSR":"Corporate social responsibility",
    "CRM":"Customer Relationship Management",
    "CVP":"Cost Volume Profit",
    "CTA":"Call to action",
    "CTO":"Chief Technology Officer",
    "CX":"Customer Experience",
    "CXO":"Any chief officer(s)",
    "C2B":"Consumer-to-business",
    "C&F":"Cost With Freight",
    "CKM":"Customer Knowledge Management",
    "CTC":"Cost to company",
    "CUSIP":"Committee on Uniform Security Identification",
    "Cr":"Credit",
    "CA":"Current account",
    "CPA":"Cost Per Action",
    "CPL":"Cost Per Lead",
    "CR":"Conversion Rate",
    "CTA":"Call to Action",
    "CAC":"Customer Acquisition Cost",
    "API":"Application Programming Interface",
    "ARR":"Annual Recurring Revenue",
    "MRR":"Monthly Recurring Revenue",
    "GTM":"Go-To-Market",
    "LTV":"Customer Lifetime Value",
    "KPI":"Key Performance Indicators",
    "JTBD":"Jobs To Be Done",
    "MVP":"Minimum Viable Product",
    "TAM":"Total Addressable Market",
    "UI":"User Interface",
    "UX":"User Experience",
    "POC":"Proof Of Concept",
    "USP":"Unique Selling Proposition",
    "DAU":"Daily Active Users",
    "MAU":"Monthly Active Users",
    "DDA":"Depletion Depreciation Amortization",
    "Dept":"Department",
    "DCF":"Discounted Cash Flow",
    "DI":"Dispatch information",
    "DIFOT":"Delivery in full on time",
    "Dir":"Director",
    "disc":"Discount",
    "DMA":"Direct market access",
    "DOE":"Depending on Experience",
    "DPO":"Days Payable Outstanding",
    "DR":"Depositary receipt",
    "DSO":"Days Sales Outstanding",
    "DSP":"Delivery service provider",
    "DTP":"Desktop Publishing",
    "DVP":"Delivery versus payment",
    "D2C":"Direct-To-Consumer",
    "EAR":"Effective annual rate",
    "EAY":"Effective Annual Yield",
    "EBITA":"Earnings before interest and taxes",
    "EBITDA":"Earnings before Interest",
    "ECB":"European Central Bank",
    "ECS":"Electronic Clearing Service",
    "EDI":"Electronic Data Interchange",
    "EFSM":"European Financial Stabilisation Mechanism",
    "EFTPOS":"Electronic Funds Transfer at Point",
    "EIDL":"Economic Injury Disaster Loan",
    "EPS":"Earnings per share",
    "EXP":"Export",
    "EOB":"End of business",
    "EOD":"End of day",
    "EOM":"End of Message",
    "ERP":"Enterprise Resource Planning",
    "ETA":"Estimated Time of Arrival",
    "ETD":"Estimated Time of Departure",
    "EMI":"Equated Monthly Installment",
    "EPC":"Export Promotion Council",
    "ECGC":"Export Credit Guarantee Corporation of",
    "EXW":"Ex Works",
    "FAB":"Feature Advantage Benefits",
    "FDP":"Finance Department",
    "FOB":"Freight On Board",
    "FIFO":"First In",
    "FinMin":"Finance Minister",
    "FL":"Financial leverage",
    "FOMC":"Federal Open Market Committee",
    "FP&A":"Financial Planning & Analysis",
    "FPO":"Follow-on Public Offer",
    "FIX":"Financial Information Exchange",
    "FSA":"Financial Services Authority",
    "FTE":"Full-Time Equivalent",
    "FV":"Future Value",
    "FX":"Foreign exchange market",
    "FY":"Fiscal year or Financial year",
    "FYA":"For Your Action",
    "FYI":"For Your Information",
    "FOC":"Free Of Cost",
    "F/U":"Follow-Up",
    "FYF":"Full Year Forecast",
    "GAAP":"Generally Accepted Accounting Principles",
    "GAAS":"Generally Accepted Audit Standards",
    "GDP":"Gross Domestic Product",
    "GDPR":"General Data Protection Regulation",
    "GDR":"Global depository receipt",
    "GFCF":"Gross fixed capital formation",
    "GL":"General Ledger",
    "GMV":"Gross Merchandise Volume",
    "GP":"Gross Profit",
    "GPO":"Group purchasing organization",
    "GRN":"Goods Receipt Note",
    "GRNI":"Goods Receipt Not Invoiced",
    "GSV":"Gross Sales Value",
    "GVC":"Global value chain",
    "GMROII":"Gross Margin Return on Inventory Investment",
    "G&A":"General and Administration expense",
    "HMRC":"Her Majesty's Revenue and Customs",
    "HP":"Hire purchase",
    "HQ":"Headquarters",
    "HR":"Human Resources",
    "HRD":"Human Resource Development",
    "HS Code":"Harmonized Commodity Description and Coding System",
    "IAS":"International Accounting Standards",
    "IBAN":"International Bank Account Number",
    "ICB":"Industry Classification Benchmark",
    "ICRM":"Innovative Customer Relationship Management",
    "IE":"Interest expense",
    "IFRS":"International Financial Reporting Standard",
    "ILCLP":"IdentLogic Systems Customer Loyalty Program",
    "IMF":"International Monetary Fund",
    "IMP":"Import",
    "Inc":"Incorporated",
    "IoT":"Internet of Things",
    "IPO":"Initial public offering",
    "IPT":"Item Per Transaction",
    "IR":"Interest rate",
    "IRS":"Internal Revenue Service",
    "IRR":"Internal Rate of Return",
    "ISIN":"International Securities Identification Number",
    "ISM":"Institute of Supply Management",
    "ITT":"Invitation to tender",
    "IYR":"In Year Revenue",
    "JIT":"Just in time",
    "JIS":"Just in sequence",
    "JST":"Joint Supervisory Team",
    "JV":"Joint Venture",
    "KIBOR":"Karachi Interbank Offered Rate",
    "KPI":"Key Performance Indicator",
    "KYC":"Know Your Customer",
    "LBO":"Leveraged Buyout",
    "LC":"Letter of credit",
    "LIBOR":"London Interbank Offered Rate",
    "LE":"Latest Estimate",
    "LIFFE":"London International Financial Futures and and Options Exchange",
    "LIFO":"Last In",
    "LLC":"Limited Liability Company",
    "LME":"London Metal Exchange",
    "LMS":"Learning Management System",
    "Ltd":"Limited Company",
    "LTV":"Loan to Value",
    "LOC":"Lines of Credit",
    "LOI":"Letter of intent",
    "LoU":"Letters of Undertaking",
    "LY":"Last Year",
    "MBS":"Mortgage-backed security",
    "mfg":"Manufacturing",
    "MGMT":"Management",
    "MIC":"Market Identifier Code",
    "MiFID":"Markets in Financial Instruments Directive",
    "MILE":"Maximum impact",
    "MoM":"Month on Month",
    "MOQ":"Minimum Order Quantity",
    "MOU":"Memorandum of understanding",
    "MPC":"marginal propensity to consume",
    "MRO":"Maintenance",
    "MRP":"Maximum Retail Price",
    "MSOD":"Monthly Statement of Select Operational",
    "MSRP":"Manufacturer's Suggested Retail Price",
    "MTD":"Month-to-date",
    "MWC":"Managerial Working Capital",
    "MPR":"Monthly Progress Report",
    "MTM":"Mark To Market",
    "NAV":"Net asset value",
    "NCBO":"No Change of Beneficial Ownership",
    "NCND":"Non-Circumvent and Non-Disclosure",
    "NDA":"Non-Disclosure Agreement",
    "NII":"Net Interest Income",
    "NIM":"Net Interest Margin",
    "NNTO":"No Need To Open",
    "NOA":"Net Operating Assets",
    "NOI":"Net Operating Income",
    "NOPAT":"Net Operating Profit After Tax",
    "NPA":"Non Performing Asset",
    "NPL":"Non-performing loan",
    "NPV":"Net Present Value",
    "NTE":"Not To Exceed",
    "NYMEX":"New York Mercantile Exchange",
    "NYSE":"New York Stock Exchange",
    "NFO":"New Fund Offer",
    "OC":"Opportunity Cost",
    "OCF":"Operating cash flow",
    "OECD":"Organisation for Economic Co-operation and Development",
    "OEM":"Original Equipment Manufacturer",
    "OIBDA":"Operating Income Before Depreciation And Amortization",
    "OKR":"Objectives and key results",
    "OOF":"Out of Facility",
    "OOO":"Out of Office",
    "OPEX":"Operational Expenditure",
    "OTIF":"On Time In Full",
    "OTC":"Over-the-counter (finance)",
    "P&L":"Profit and Loss",
    "P2B":"Platform to Business",
    "PA":"Purchasing agent or Personal Assistant",
    "PA":"Promotional Activity[citation needed]",
    "PAT":"Profit After Tax",
    "PBT":"Profit Before Tax",
    "P/E":"Price-to-earnings ratio",
    "PE":"Private Equity",
    "PEG":"Price-to-earnings growth ratio",
    "PHEK":"Planherstellungskosten (Product Planning cost)",
    "PFI":"Private Finance Initiative",
    "PII":"Personally identifiable information",
    "pip":"Percentage in point or Periodic Investment Plan",
    "PMAC":"Period Moving Average Cost",
    "PO":"Profit Objective or Purchase Order",
    "POA":"Plan Of Action",
    "POS":"Point of sale",
    "PP&E":"Property, Plant, and Equipment",
    "PPP":"Public-private partnership",
    "PPP":"Purchasing power parity",
    "PPT":"Powerpoint presentation",
    "PR":"Purchase Requisition",
    "PSP":"Profit Sharing Plan",
    "PTC":"Private Trust Company",
    "PTD":"Project to Date",
    "PLR":"Prime Lending Rate",
    "PWIN":"Percent win",
    "PWP":"Personal Wealth Portfolio",
    "QC":"Quality control or Quality costs",
    "QoQ":"Quarter on quarter",
    "QPR":"Quarterly Performance Report",
    "QRP":"Qualified Retirement Plan",
    "q/q":"Quarter on quarter",
    "QTD":"Quarter-to-date",
    "RAQSCI":"Regulatory",
    "RBI":"Reserve Bank of India",
    "RBA":"Reserve Bank of Australia",
    " RE":"Retained Earnings",
    "REIT":"Real Estate Investment Trust",
    "RFI":"Request for information",
    "RFP":"Request for Proposal",
    "RFQ":"Request for Quotation",
    "RFX":"Generic name for a Request for Information",
    "RMD":"Required Minimum Distribution",
    "R/O":"Rollover",
    "ROA":"Return on assets",
    "ROB":"Return on brand",
    "ROC":"Registration Of Company",
    "ROCE":"Return on Capital Employed",
    "ROE":"Return on Equity",
    "ROI":"Return on Investment",
    "ROIC":"Return on Invested Capital",
    "RONA":"Return on net assets",
    "ROS":"Return on Sales",
    "RR":"Resource rent",
    "RSP":"Retail selling price",
    "RWA":"Risk-weighted asset",
    "R&D":"Research and Development",
    "RC":"Retail Company",
    "S&M":"Sales & Marketing",
    "SLR":"Statutory Liquidity Ratio",
    "S&OP":"Sales and operations planning",
    "SAAS":"Software-as-a-Service",
    "SAM":"Strategic Asset Management",
    "SBU":"Strategic Business Unit",
    "SBLC":"Stand By Letter of Credit",
    "SCM":"Supply Chain Management",
    "SCBA":"Social Cost Benefit Analysis",
    "SEBI":"Securities and Exchange Board of",
    "SEC":"Securities and Exchange Commission",
    "SEDOL":"Stock Exchange Daily Official List",
    "SF":"Structured Finance",
    "SG&A":"sales, general and administrative expenses",
    "SIMPLE":"Savings Incentive Match Plan for",
    "SIOP":"Sales Inventory and Operations Plan",
    "SIR":"Stores Issuance Requisition",
    "SIV":"Structured investment vehicle",
    "SKU":"Stock keeping unit",
    "SLA":"Service Level Agreement",
    "SMA":"Separately Managed Account",
    "SME":"Small and Medium Enterprises",
    "SOHO":"Small Office/Home Office",
    "SOP":"Standard Operating Procedure",
    "SOW":"Statement of Work",
    "SOX":"Sarbanes-Oxley",
    "SPP":"Systematic Payment Plan",
    "SROI":"Social return on investment",
    "SSN":"Social Security Number",
    "Stg":"Sterling",
    "STP":"Situation Target Proposal",
    "SUA":"Start Up Agreement",
    "SWM":"Strategic Wealth Management",
    "SWIP":"Systematic Withdrawal from Investment Plan",
    "SWOT":"Strengths, Weaknesses, Opportunities, Threats",
    "TB":"Transaction Banking",
    "TBC":"To Be Completed",
    "TBD":"To Be Defined",
    "TCO":"Total Cost of Ownership",
    "TCV":"Total Contract Value",
    "TOTW":"Time Off for Time Worked",
    "TQM":"Total Quality Management",
    "TSR":"Total shareholder return",
    "TTM":"Trailing Twelve Months",
    "TVM":"Time Value of Money",
    "Ts&Cs":"Terms and Conditions",
    "USP":"Unique Selling Proposition",
    "UPI":"Unified Payment Interface",
    "VAD":"Value-Added Distributor",
    "VaR":"Value at Risk",
    "VAT":"Value-Added Tax",
    "VC":"Venture Capital",
    "VP":"Vice President",
    "WACC":"Weighted average cost of capital",
    "WC":"Working capital",
    "WFH":"Work From Home",
    "wk":"week",
    "wrk":"work",
    "wo":"work order",
    "WOGs":"With other Goods",
    "WIGs":"Wildly Important Goals",
    "wasp":"weighted average selling price",
    "WLL":"With Limited Liability",
    "wrt":"With Respect To",
    "WTI":"West Texas Intermediate",
    "WVN":"Withdraw Voucher Note",
    "WHT":"Withholding Tax",
    "WTO":"World Trade Organization",
    "WTD":"Week-To-Date",
    "WW":"World Wide",
    "YTD":"Year-to-date",
    "YTG":"Year-to-go",
    "YOY":"Year-over-year",
    "YTC":"Yet-To-Confirm",
    "ZBB":"Zero Based Budgeting",
    "ZCYC":"Zero Coupon Yield Curve",
    "ZOPA":"Zone of Possible Agreement",
    "AUD":"Australia Dollar",
    "GBP":"Great Britain Pound",
    "EUR":"Euro",
    "JPY":"Japan Yen",
    "CHF":"Switzerland Franc",
    "USD":"USA Dollar",
    "AFN":"Afghanistan Afghani",
    "DZD":"Algeria Dinar",
    "AOA":"Angola Kwanza",
    "ARS":"Argentina Peso",
    "AMD":"Armenia Dram",
    "AWG":"Aruba Florin",
    "AUD":"Australia Dollar",
    "ATS (EURO)":"Austria Schilling",
    "BEF (EURO)":"Belgium Franc",
    "AZN":"Azerbaijan New Manat",
    "BSD":"Bahamas Dollar",
    "BHD":"Bahrain Dinar",
    "BDT":"Bangladesh Taka",
    "BBD":"Barbados Dollar",
    "BYR":"Belarus Ruble",
    "BZD":"Belize Dollar",
    "BMD":"Bermuda Dollar",
    "BTN":"Bhutan Ngultrum",
    "BOB":"Bolivia Boliviano",
    "BAM":"Bosnia Mark",
    "BWP":"Botswana Pula",
    "BRL":"Brazil Real",
    "GBP":"Great Britain Pound",
    "BND":"Brunei Dollar",
    "BGN":"Bulgaria Lev",
    "BIF":"Burundi Franc",
    "XOF":"CFA Franc BCEAO",
    "XAF":"CFA Franc BEAC",
    "XPF":"CFP Franc",
    "KHR":"Cambodia Riel",
    "CAD":"Canada Dollar",
    "CVE":"Cape Verde Escudo",
    "KYD":"Cayman Islands Dollar",
    "CLP":"Chili Peso",
    "CNY":"China Yuan/Renminbi",
    "COP":"Colombia Peso",
    "KMF":"Comoros Franc",
    "CDF":"Congo Franc",
    "CRC":"Costa Rica Colon",
    "HRK":"Croatia Kuna",
    "CUC":"Cuba Convertible Peso",
    "CUP":"Cuba Peso",
    "CYP (EURO)":"Cyprus Pound",
    "CZK":"Czech Koruna",
    "DKK":"Denmark Krone",
    "DJF":"Djibouti Franc",
    "DOP":"Dominican Republich Peso",
    "XCD":"East Caribbean Dollar",
    "EGP":"Egypt Pound",
    "SVC":"El Salvador Colon",
    "EEK (EURO)":"Estonia Kroon",
    "ETB":"Ethiopia Birr",
    "EUR":"Euro",
    "FKP":"Falkland Islands Pound",
    "FIM (EURO)":"Finland Markka",
    "FJD":"Fiji Dollar",
    "GMD":"Gambia Dalasi",
    "GEL":"Georgia Lari",
    "DMK (EURO)":"Germany Mark",
    "GHS":"Ghana New Cedi",
    "GIP":"Gibraltar Pound",
    "GRD (EURO)":"Greece Drachma",
    "GTQ":"Guatemala Quetzal",
    "GNF":"Guinea Franc",
    "GYD":"Guyana Dollar",
    "HTG":"Haiti Gourde",
    "HNL":"Honduras Lempira",
    "HKD":"Hong Kong Dollar",
    "HUF":"Hungary Forint",
    "ISK":"Iceland Krona",
    "INR":"India Rupee",
    "IDR":"Indonesia Rupiah",
    "IRR":"Iran Rial",
    "IQD":"Iraq Dinar",
    "IED (EURO)":"Ireland Pound",
    "ILS":"Israel New Shekel",
    "ITL (EURO)":"Italy Lira",
    "JMD":"Jamaica Dollar",
    "JPY":"Japan Yen",
    "JOD":"Jordan Dinar",
    "KZT":"Kazakhstan Tenge",
    "KES":"Kenya Shilling",
    "KWD":"Kuwait Dinar",
    "KGS":"Kyrgyzstan Som",
    "LAK":"Laos Kip",
    "LVL (EURO)":"Latvia Lats",
    "LBP":"Lebanon Pound",
    "LSL":"Lesotho Loti",
    "LRD":"Liberia Dollar",
    "LYD":"Libya Dinar",
    "LTL (EURO)":"Lithuania Litas",
    "LUF (EURO)":"Luxembourg Franc",
    "MOP":"Macau Pataca",
    "MKD":"Macedonia Denar",
    "MGA":"Malagasy Ariary",
    "MWK":"Malawi Kwacha",
    "MYR":"Malaysia Ringgit",
    "MVR":"Maldives Rufiyaa",
    "MTL (EURO)":"Malta Lira",
    "MRO":"Mauritania Ouguiya",
    "MUR":"Mauritius Rupee",
    "MXN":"Mexico Peso",
    "MDL":"Moldova Leu",
    "MNT":"Mongolia Tugrik",
    "MAD":"Morocco Dirham",
    "MZN":"Mozambique New Metical",
    "MMK":"Myanmar Kyat",
    "ANG":"NL Antilles Guilder",
    "NAD":"Namibia Dollar",
    "NPR":"Nepal Rupee",
    "NLG (EURO)":"Netherlands Guilder",
    "NZD":"New Zealand Dollar",
    "NIO":"Nicaragua Cordoba Oro",
    "NGN":"Nigeria Naira",
    "KPW":"North Korea Won",
    "NOK":"Norway Kroner",
    "OMR":"Oman Rial",
    "PKR":"Pakistan Rupee",
    "PAB":"Panama Balboa",
    "PGK":"Papua New Guinea Kina",
    "PYG":"Paraguay Guarani",
    "PEN":"Peru Nuevo Sol",
    "PHP":"Philippines Peso",
    "PLN":"Poland Zloty",
    "PTE (EURO)":"Portugal Escudo",
    "QAR":"Qatar Rial",
    "RON":"Romania New Lei",
    "RUB":"Russia Rouble",
    "RWF":"Rwanda Franc",
    "WST":"Samoa Tala",
    "STD":"Sao Tome/Principe Dobra",
    "SAR":"Saudi Arabia Riyal",
    "RSD":"Serbia Dinar",
    "SCR":"Seychelles Rupee",
    "SLL":"Sierra Leone Leone",
    "SGD":"Singapore Dollar",
    "SKK (EURO)":"Slovakia Koruna",
    "SIT (EURO)":"Slovenia Tolar",
    "SBD":"Solomon Islands Dollar",
    "SOS":"Somali Shilling",
    "ZAR":"South Africa Rand",
    "KRW":"South Korea Won",
    "ESP (EURO)":"Spain Peseta",
    "LKR":"Sri Lanka Rupee",
    "SHP":"St Helena Pound",
    "SDG":"Sudan Pound",
    "SRD":"Suriname Dollar",
    "SZL":"Swaziland Lilangeni",
    "SEK":"Sweden Krona",
    "CHF":"Switzerland Franc",
    "SYP":"Syria Pound",
    "TWD":"Taiwan Dollar",
    "TZS":"Tanzania Shilling",
    "THB":"Thailand Baht",
    "TOP":"Tonga Pa'anga",
    "TTD":"Trinidad/Tobago Dollar",
    "TND":"Tunisia Dinar",
    "TRY":"Turkish New Lira",
    "TMM":"Turkmenistan Manat",
    "USD":"USA Dollar",
    "UGX":"Uganda Shilling",
    "UAH":"Ukraine Hryvnia",
    "UYU":"Uruguay Peso",
    "AED":"United Arab Emirates Dirham",
    "VUV":"Vanuatu Vatu",
    "VEB":"Venezuela Bolivar",
    "VND":"Vietnam Dong",
    "YER":"Yemen Rial",
    "ZMK":"Zambia Kwacha",
    "ZWD":"Zimbabwe Dollar"
}

// object (dictionary) with term-definition pairs
let finTerms = {
  "Accounts payable":"a record of all unpaid short-term (less than 12 months) invoices, bills and other liabilities. Examples of accounts payable include invoices for goods or services, bills for utilities and tax payments due.",
  "Accounts receivable":"a record of all short-term accounts (less than 12 months) from customers you sell to but are yet to pay. These customers are called debtors and are generally invoiced by a business.",
  "Accrual accounting":"an accounting system that records transactions at the time they occur, whether the payment occurs now or in the future.",
  "Amortisation":"the process of offsetting assets such as goodwill and intellectual property over a period of time. See also Depreciation.",
  "Assets":"things you own. These can be cash or something you can convert into cash such as property, vehicles, equipment and inventory.",
  "Audit":"a check by an auditor or tax official on your financial records to check that you account for everything correctly.",
  "Bad debts":"money that is unlikely to be paid in the near future.",
  "Balance sheet":"a snapshot of a business on a particular date. It lists all of your assets and liabilities and works out the net assets.",
  "Balloon payment":"a final lump sum payment due on a loan agreement. Loans with a larger final 'balloon payment' have lower regular repayments over the term of the loan.",
  "Bank reconciliation":"a cross-check that ensures the amounts in your cashbook match the relevant bank statements.",
  "Bankruptcy":"a process where an individual is legally bankrupt and an appointed trustee manages their assets and financial affairs.",
  "Benchmark":"a set of conditions against which you can measure a product or business.",
  "Bill of sale":"a legal document for the purchase of property or other assets that details the purchase, where it took place, and for how much.",
  "Bookkeeping":"the process of recording the financial transactions of a business.",
  "Bootstrapping":"where a business funds its growth purely through personal finances and revenue from the business.",
  "Bottom line":"see Net profit.",
  "Break-even point":"the exact point when a business's income equals its expenses.",
  "Capital cost":"a one-off substantial purchase of physical items such as plant, equipment, building or land.",
  "Capital gain":"the amount gained when an asset sells above its original purchase price.",
  "Capital growth":"an increase in the value of an asset.",
  "Cash":"includes all money available on demand, including bank notes and coins, petty cash, certain cheques, and money in savings or debit accounts.",
  "Cash accounting":"an accounting system that records transactions at the time you actually receive money payment.",
  "Cash book":"a daily record of all cash, credit or cheque transactions received or paid out by a business.",
  "Cash flow":"the measure of actual cash flowing in and out of a business.",
  "Collateral":"see Security.",
  "Commercial bill (also known as a bill of exchange)":"a form of commercial loan on an interest only basis, or interest reducing basis. Commercial bills typically require some sort of security and suit short-term funding needs such as inventory.",
  "Contingent liability":"a liability where payment is made only if a particular event or circumstance occurs.",
  "Cost of goods sold":"the total direct costs of producing a good or delivering a service.",
  "Creditor":"a person or business that allows you to purchase a good or service with an agreement to pay at a later date. A creditor is also anyone who you owe money to, such as a lender or supplier.",
  "Credit limit":"a dollar amount that you cannot exceed on a credit card or the maximum lending amount offered for a loan.",
  "Credit rating":"a ranking applied to a person or business based on their credit history that represents their ability to repay a debt. Visit ASIC’s MoneySmart website to learn more about credit ratings- external site.",
  "Credit history":"a report detailing an individual's or business's past credit arrangements. A lender may seek a credit history when assessing a loan application. Visit ASIC’s MoneySmart website to read more about credit reports- external site.",
  "Crowdfunding":"is a way of financing your business idea through donations of money from the public. This usually occurs online, through a crowdfunding website.",
  "Current asset":"an asset in cash or something you can convert into cash within 12 months.",
  "Current liability":"a liability that is due for payment within 12 months.",
  "Debit":"in double-entry bookkeeping, a debit is an entry made on the left-hand side of a journal or ledger representing an asset or expense.",
  "Debt":"any amount that you owe including bills, loan repayments and income tax.",
  "Debt consolidation":"the process of combining several loans or other debts into one for the purposes of obtaining a lower interest rate or reducing fees.",
  "Debt finance":"money provided by an external lender, such as a bank or building society.",
  "Debtor":"a person or business that owes you money.",
  "Debtors finance":"See Factoring.",
  "Default":"a failure to pay a loan or other debt obligation.",
  "Depreciation":"the process of offsetting an asset over a period of time. You can depreciate an asset to spread the cost of the asset over its useful life.",
  "Disbursements":"money that a business spends.",
  "Double-entry bookkeeping":"is a bookkeeping method that records each transaction in 2 accounts, both as a debit and a credit.",
  "Drawings":"personal expenses paid for from a business account.",
  "Drip pricing- external site":"is when one price is presented at the beginning of an online shopping experience. Gradually, incremental fees and charges are added (or 'dripped') as you progress, for example, when buying a plane ticket. Drip pricing can result in the customer paying a higher price for a service or product than they first thought. However, you are required to show fees and charges at the beginning of an online shopping process and not gradually add them in.",
  "Employee share schemes- external site":"where you give your employees the opportunity to buy shares in your company. Other terms include an 'employee share purchase plan' or an 'employee equity scheme'.",
  "Encumbered":"an encumbered asset is one that is currently put forward as security or collateral for a loan.",
  "Equity":"the value of ownership interest in the business, calculated by deducting liabilities from assets. See also Owner's equity.",
  "Equity finance":"money provided to a business in exchange for part ownership of the business. This can be money invested by the business owners, friends, family, or investors like business angels and venture capitalists.",
  "Excise duty":"an indirect tax levied on certain types of goods produced or manufactured in Australia including petrol, alcohol, tobacco and coal.",
  "Facility":"an arrangement such as an account offered by a financial institution to a business (such as a bank account, a short-term loan or overdraft).",
  "Factoring (also known as debtor’s finance and accounts receivable finance)":"when a factor company buys a business's outstanding invoices at a discount. The factor company then chases up the debtors. Factoring is a way to get quick access to cash, but can be quite expensive compared to traditional financing options.",
  "Finance":"money used to fund a business or high value purchase.",
  "Financial year":"a 12-month period typically from 1 July to 30 June.",
  "Financial statement":"a summary of a business's financial position for a given period. Financial statements can include a profit and loss, balance sheet and cash flow statement.",
  "Fixed asset":"a physical asset used in the running of a business.",
  "Fixed cost":"a cost that is not part of producing a good or service.",
  "Forecast":"a list of future financial transactions. Forecasts help to plan a more accurate budget.",
  "Fringe benefits":"non-monetary benefits, such as company cars and mobile phones, included as part of a salary package.",
  "Fully drawn advance":"is a long term loan with the option to fix the interest rate for a period. These loans are usually secured and can help fund a new business or equipment.",
  "Goodwill":"an intangible asset that represents the value of a business's reputation.",
  "Gross income":"the total money earned by a business before you deduct expenses.",
  "Gross profit (also known as net sales)":"the difference between sales and the direct cost of making the sales.",
  "Guarantor":"a person who promises to pay a loan in the event the borrower cannot meet the repayments. The guarantor is legally responsible for the debt.",
  "Hire-purchase":"a type of contract where you purchase a good through an initial deposit. You then rent it and pay the balance off in instalments plus interest charges. When you make the final payment, ownership of the good transfers to the purchaser. See also Rent to buy.",
  "Initial public offering (IPO)":"when a company first offers shares on the stock market to sell them to the general public. Also known as floating on the stock market. Visit ASIC’s MoneySmart website for more information about IPOs- external site.",
  "Insolvent":"a business or company is insolvent when they cannot pay their debts as and when they are due.",
  "Intangible assets":"non-physical assets with no fixed value, such as goodwill and intellectual property rights.",
  "Interest":"the cost of borrowing money on a loan or earned on an interest-bearing account.",
  "Interest rate":"a percentage used to calculate the cost of borrowing money or the amount you will earn. Rates vary from product to product and generally the higher the risk of the loan, the higher the interest rate. Rates may be fixed or variable.",
  "Inventory":"a list of goods or materials a business is holding for sale.",
  "Invoice":"a document to a customer to request payment for a good or service received.",
  "Invoice finance":"finance based on the strength of a business's accounts receivable. This form of financing is similar to factoring, except that the invoices or accounts receivable remain with the business. See also Factoring.",
  "Liability":"any financial expense or amount owed.",
  "Line of credit":"an agreement allowing a borrower to withdraw money from an account up to an approved limit.",
  "Liquidate":"to quickly sell all the assets of a company and convert them into cash.",
  "Liquidation":"the process of winding up an insolvent company. An appointed administrator will do this by ceasing business operations, selling assets, and paying creditors and shareholders.",
  "Liquidity":"how quickly you can convert assets into cash.",
  "Loan":"a finance agreement where a business borrows money and pays it back in instalments (plus interest) within a specified period of time.",
  "Margin call":"when the value of a property or asset falls below a certain loan to value ratio (LVR). For higher risk loans such as margin loans, the lender will request further payment to bring the LVR back to the agreed percentage. See also Loan to value ratio (LVR).",
  "Mark down":"a discount applied to a product during a promotion or sale for the purposes of attracting sales or for shifting surplus or discontinued products. See also Discount.",
  "Mark up":"the amount added to the cost price of goods, to help determine a selling price. Essentially it is the difference between the cost of the good/service and the selling price. It does not take into account what proportion of the amount is profit.",
  "Maturity date":"when a loan's term ends and all outstanding principal and interest payments are due.",
  "Net assets (also known as net worth, owner's equity or shareholder's equity)":"the total assets minus total liabilities.",
  "Net income":"the total money earned by a business after tax and other deductions.",
  "Overdraft facility":"a finance arrangement where a lender allows a business to withdraw more than the balance of an account.",
  "Overdrawn account":"a credit account that has exceeded its credit limit or a bank account that has had more than the remaining balance withdrawn.",
  "Overheads":"the fixed costs associated with operating a business such as rent, marketing, utilities and administrative costs. See also Fixed costs.",
  "Personal property":"covers any property someone can own, except for land, buildings and fixtures. Examples include goods, plant and equipment, cars, boats, planes, livestock and more.",
  "Personal Property Security Register (PPSR)":"the PPSR- external site replaces a number of registers of security interests. It provides a single national noticeboard of security interests in personal property.",
  "Petty cash":"cash for small miscellaneous purchases such as postage.",
  "Plant and equipment":"a group of fixed assets used in the operation of a business such as furniture, machinery, fit-out, vehicles, computers and tools.",
  "Principal":"the original loan amount borrowed or the remainder of the original borrowed amount that is still owing (excluding the interest portion).",
  "Profit":"the total revenue a business earns minus the total expenses. See also Revenue.",
  "Profit and loss statement (also known as an income statement)":"a financial statement listing sales and expenses. Use it to work out the gross and net profit of a business.",
  "Profit margin":"see Margin.",
  "Projection":"see Forecast.",
  "R&D":"stands for 'research and development'. Businesses conduct research and development to innovate, create new products and find better ways of doing things.",
  "Receipts":"a document given to a customer to confirm payment and to confirm the sale of a good or service.",
  "Record keeping":"the process of keeping or recording information that explains certain business transactions. Record keeping is a requirement under tax law.",
  "Refinance":"when a new loan helps to pay off an existing one. Reasons to refinance include: extending the original loan over a longer period of time, reduce fees or interest rates, switch banks, or move from a fixed to variable loan.",
  "Rent to buy":"a finance arrangement where you purchase something through an initial deposit and then 'lease' it while pay it off. After the final payment, the purchaser has the option (but no obligation) to buy the good or continue leasing. See also Hire-purchase.",
  "Repossess":"the process of a bank or other lender taking ownership of property/assets for the purpose of paying off a loan in default.",
  "Retention of title":"a clause in contracts where a buyer may receive property, but doesn’t take legal ownership until the full price is paid.",
  "Return on investment (ROI)":"a calculation that works out how efficient a business is at generating profit from the original equity from the owners/shareholders. It's a way of thinking about the benefit (return) of the money you invest into the business. To calculate ROI, divide the gain (net profit) of the investment by the cost of the investment. The ROI then becomes a percentage or a ratio.",
  "Revenue (also known as turnover)":"the amount earned before expenses, tax and other deductions.",
  "Single-entry bookkeeping":"a bookkeeping method within a cash accounting system that records one side of each transaction.",
  "Scam":"a deliberate and targeted deception to obtain money or information unlawfully.",
  "Security (also known as collateral)":"property or assets that a lender can take ownership of when repayment of a loan does not occur.",
  "Shareholder's equity":"see Net assets.",
  "SMSF":"stands for self-managed superannuation fund- external site. An SMSF is a way of saving for your retirement. Unlike other super funds, an SMSF is self-managed, which means you're responsible for making sure the super fund complies with super and tax laws. ASIC's MoneySmart also has useful information on SMSFs- external site.",
  "Stock":"the actual goods or materials a business currently has on hand.",
  "Stocktaking":"a regular process involving a physical count of merchandise and supplies actually held by a business, to verify stock records and accounts.",
  "Superannuation":"money set aside for retirement that must go into a complying superannuation fund. There is useful information on ASIC's MoneySmart website about businesses paying their employees super- external site.",
  "Tax invoice":"an invoice required for the supply of goods or services over a certain price. You need a valid tax invoice when claiming GST credits. See also Invoice.",
  "Turnover":"See Revenue.",
  "Variable interest rate":"when the interest rate of a loan changes with market conditions for the duration of the loan.",
  "Variable cost":"a cost that changes depending on the number of goods produced or the demand for the products or service.",
  "Venture capital":"an investment in a start-up business that has excellent growth prospects. However, it does not have access to capital markets because it is a private company.",
  "Working capital":"the cash available to a business for day-to-day expenses.",
  "Alpha":"The amount of return expected from an investment from its inherent value.",
  "Beta":"A measurement of how volatile subject is, where 1 is neutral; above 1 is more volatile; and less than 1 is less volatile.",
  "Capital gain":"The difference between a security's purchase price and its selling price, when the difference is positive.",
  "Volatility":"The amount and frequency with which an investment fluctuates in value.",
  "YTD":"Year-to-date return on an investment including appreciation and dividends or interest."
}

// func to get all the text nodes under a particular node
function textNodesUnder(el) {
  var n, a=[], walk=document.createTreeWalker(el,NodeFilter.SHOW_TEXT,null,false);
  while(n=walk.nextNode()) a.push(n);
  return a;
}

// getting textnodes from the body of the document
const pageText = textNodesUnder(document.body);

// execute main func
acronymize(pageText)

// walking through each of the node in the page text
// if word in the node (in the page text) matches dictionary key, 
// then replace the word for dictionary value
function acronymize(pageText) {
  for (node of pageText) {
    var origText = node.nodeValue;
    var text = origText;
    var term = origText;
    for (const key of Object.keys(finTerms)) {
      var pattern = new RegExp(`\\b${key}\\b`, 'ig');
      var replacement = '<span class="tooltip">' + "[" + key + "]" + 
                            '<span class="tooltiptext" style="height:fit-content">' + 
                            finTerms[key] + '</span></span>';
      var newTerm = term.replace(pattern, replacement);
      if ((newTerm !== term) && 
        (node.parentNode !== null)) {
          term = newTerm;
      }
    } 
    for (const key of Object.keys(finAcronyms)) {
      var pattern = new RegExp(`\\b${key}\\b`, 'ig');
      var replacement = `[${finAcronyms[key]}]`
      var newText = text.replace(pattern, replacement);
      if ((newText !== text) && 
        (node.parentNode !== null) && 
        !(origText.includes(`${finAcronyms[key]}`))) {
          text = newText;
        }
    }
    if ((term != origText) && (node.parentNode !== null)){
      var elementTerm = document.createElement("span");
      elementTerm.innerHTML = term;
      node.parentNode.replaceChild(elementTerm, node);
    }
    if ((text != origText) && (node.parentNode !== null)) {
      var elementText = document.createElement("span");
      elementText.innerHTML = text;
      node.parentNode.replaceChild(elementText, node);
    }
  }
}

/////////////////////////////////////